    const datos ={
        "apellidos": "SORA OLAYA",
        "nombres": "YOVANY",
        "edad": 34,
        "nacionalidad": "ALBANIA",
        "identificacion": "79947229",
        "paisExp": "ALBANIA",
        "deptoExp": "Antioquia",
        "paisNacimiento": "AUSTRALIA",
        "ciudadNacimiento": "CHAGUANÍ",
        "genero": "Femenino",
        "rh": "O-",
        "estadoCivil": "Casado (A)",
        "grupoEtnico": "Ninguno",
        "cabezaFamilia": "Si",
        "emailPersonal": "rte",
        "celularPersonal": "eert",
        "emailCorporativo": "ert",
        "celularCorporativo": "ert",
        "ocupacion": "Empleado",
        "tipoContrato": "TERMINO INDEFINIDO",
        "fechaIngreso": "01-09-2004",
        "departamento": "DSERVCL",
        "cargo": "DIRECTOR SERVICE DESK",
        "area": "QA - COSTO",
        "paisResidencia": "COREA (SUR), REPUBLICA DE",
        "dptoResidencia": "Amazonas",
        "ciudad": "LETICIA",
        "localidad": "TEUSAQUILLO",
        "direccion": "Avenida calle 1 # 1 - 1 ",
        "barrio": "ert",
        "nivelSocioec": "3",
        "tipoVivienda": "Propia",
        "tieneVehiculo": "SI",
        "nomContactoEmerg": "ert",
        "parentescoContEmerg": "Esposo/a",
        "telContactoEmergencia": "345",
        "estudiaActualmente": "No",
        "programaEnCurso": "",
        "tituloEducObtenido": "sdf",
        "Otro": "sdf",
        "nivelEducativo": "BACHILLER",
        "institucionEducativa": "sdf",
        "tarjetaProfesional": "NO",
        "deportePractica": "No",
        "cualDeporte": "",
        "frecuencia": "",
        "manejoTiempoLibre": "sdf",
        "victimaConflicto": "NO",
        "registroUnicoVict": "NO",
        "mujerVict": "NO",
        "discapaComp": "NO",
        "calificaEnCurso": "NO",
        "condEspSalud": "No",
        "cualCondEspSalud": "",
        "respPersDisc": "NO",
        "hijoEnfermTermi": "No",
        "deptoNacimiento": "Cundinamarca",
        "ciudadExp": "ABEJORRAL",
        "personasCargoList": [
            {
                "NombrePersonaCarg": "wer",
                "parenPerCarg": "Sobrino/a",
                "fchNacPerCarg": "2022-11-02",
                "edadPerCarg": 33
            },
            {
                "NombrePersonaCarg": "wer2",
                "parenPerCarg": "Yerno",
                "fchNacPerCarg": "2022-12-06",
                "edadPerCarg": 33
            },
            {
                "NombrePersonaCarg": "wer3",
                "parenPerCarg": "Tio/a",
                "fchNacPerCarg": "2022-11-15",
                "edadPerCarg": 44
            }
        ],
        "hijosList": [
            {
                "nombreHijo": "sdf",
                "fchNacHijo": "2022-11-03",
                "edadHijo": 44
            },
            {
                "nombreHijo": "sdf2",
                "fchNacHijo": "2022-11-03",
                "edadHijo": 22
            }
        ]
    }


const datospostman={
    "apellidos":"apellidos",
    "nombres":"nombres",
    "edad":"edad",
    "nacionalidad":"nacionalidad",
    "identificacion":"identificacion",
    "paisExp":"paisExp",
    "deptoExp":"deptoExp",
    "ciudadExp":"ciudadExp",
    "paisNacimiento":"paisNacimiento",
    "deptoNacimiento":"deptoNacimiento",
    "ciudadNacimiento":"ciudadNacimiento",
    "genero":"genero",
    "rh":"rh",
    "estadoCivil":"estadoCivil",
    "grupoEtnico":"grupoEtnico",
    "cabezaFamilia":"cabezaFamilia",
    "emailPersonal":"emailPersonal",
    "celularPersonal":"celularPersonal",
    "emailCorporativo":"emailCorporativo",
    "celularCorporativo":"celularCorporativo",
    "ocupacion":"ocupacion",
    "tipoContrato":"tipoContrato",
    "fechaIngreso":"fechaIngreso",
    "departamento":"departamento",
    "cargo":"cargo",
    "area":"area",
    "paisResidencia":"paisResidencia",
    "dptoResidencia":"dptoResidencia",
    "ciudad":"ciudad",
    "localidad":"localidad",
    "direccion":"direccion",
    "barrio":"barrio",
    "nivelSocioec":"nivelSocioec",
    "tieneVehiculo":"tieneVehiculo",
    "tipoVivienda":"tipoVivienda",
    "nomContactoEmerg":"nomContactoEmerg",
    "parentescoContEmerg":"parentescoContEmerg",
    "telContactoEmergencia":"telContactoEmergencia",
    "estudiaActualmente":"estudiaActualmente",
    "programaEnCurso":"programaEnCurso",
    "tituloEducObtenido":"tituloEducObtenido",
    "Otro":"Otro",
    "nivelEducativo":"nivelEducativo",
    "institucionEducativa":"institucionEducativa",
    "tarjetaProfesional":"tarjetaProfesional",
    "deportePractica":"deportePractica",
    "cualDeporte":"cualDeporte",
    "frecuencia":"frecuencia",
    "manejoTiempoLibre":"manejoTiempoLibre",
    "victimaConflicto":"victimaConflicto",
    "registroUnicoVict":"registroUnicoVict",
    "mujerVict":"mujerVict",
    "discapaComp":"discapaComp",
    "calificaEnCurso":"calificaEnCurso",
    "condEspSalud":"condEspSalud",
    "cualCondEspSalud":"cualCondEspSalud",
    "respPersDisc":"respPersDisc",
    "hijoEnfermTermi":"hijoEnfermTermi"
    }